spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: 12345
    driver-class-name: oracle.jdbc.driver.OracleDriver
  application:
    name: employee-file-sharing
  jpa:
    properties:
      hibernate:
        use_nationalized_character_data: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

server:
  port: 8080
  servlet:
    context-path: /employee-file-sharing

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace

file:
  upload-directory: employee-files
  temp-directory: temp-files
  generate-link:
    expire-hours: 24
    length: 10
